apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: build-and-deploy-pipelinerun-
spec:
  pipelineRef:
    name: build-and-deploy
  resources:
    - name: api-repo
      resourceRef:
        name: api-repo
    - name: api-image
      resourceRef:
        name: api-image
    - name: ui-repo
      resourceRef:
        name: ui-repo
    - name: ui-image
      resourceRef:
        name: ui-image